kind: ConfigMap
apiVersion: v1
metadata:
  name: nginxic
  namespace: nginxic
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
      {
            "class": "AS3",
            "declaration": {
                  "class": "ADC",
                  "schemaVersion": "3.13.0",
                  "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab9176d",
                  "label": "Example Label",
                  "remark": "Example Remark",
                  "nginxic": {
                     "class": "Tenant",
                     "nginxic": {
                        "class": "Application",
                        "template": "generic",
                        "nginx_vs_80": {
                              "class": "Service_L4",
                              "virtualPort": 80,
                              "virtualAddresses": [
                                 "10.0.0.40"
                              ],
                              "pool": "nginx_pool_80"
                        },
                        "nginx_pool_80": {
                              "class": "Pool",
                              "monitors": [
                                 "http"
                              ],
                              "members": [
                                 {
                                    "servicePort": 443,
                                    "serverAddresses": []
                                 }
                              ]
                        },
                        "nginx_vs_443": {
                              "class": "Service_L4",
                              "virtualPort": 443,
                              "virtualAddresses": [
                                 "10.0.0.40"
                              ],
                              "pool": "nginx_pool_443"
                        },
                        "nginx_pool_443": {
                              "class": "Pool",
                              "monitors": [
                                 "https"
                              ],
                              "members": [
                                 {
                                    "servicePort": 443,
                                    "serverAddresses": []
                                 }
                              ]
                        },
                        "nginx_vs_10254": {
                              "class": "Service_L4",
                              "virtualPort": 10254,
                              "virtualAddresses": [
                                 "10.0.0.40"
                              ],
                              "pool": "nginx_pool_10254"
                        },
                        "nginx_pool_10254": {
                              "class": "Pool",
                              "monitors": [
                                 "http"
                              ],
                              "members": [
                                 {
                                    "servicePort": 80,
                                    "serverAddresses": []
                                 }
                              ]
                        }
                     }
                  }
            }
         }