kind: ConfigMap
apiVersion: v1
metadata:
  name: nginxic
  namespace: nginxic
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
     {
      "class": "AS3",
      "declaration": {
            "class": "ADC",
            "schemaVersion": "3.20.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915e",
            "label": "http",
            "remark": "Demo Template",
            "nginxic": {
               "class": "Tenant"
            }
       }
     }