kind: Service
apiVersion: v1
metadata:
  name: nginxic-service-443
  namespace: nginxic
  labels:
    app: nginxic
    cis.f5.com/as3-app: nginxic
    cis.f5.com/as3-pool: nginx_pool_443
    cis.f5.com/as3-tenant: nginxic
spec:
  ports:
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: nginxic
  type: ClusterIP
